name = "threadcast-web"
compatibility_date = "2026-02-12"
compatibility_flags = ["nodejs_als"]
main = ".svelte-kit/cloudflare/_worker.js"
workers_dev = true
preview_urls = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[r2_buckets]]
binding = "THREADS_BUCKET"
bucket_name = "threadcast-threads"
